### ISSUE TITLE
How to generate pdf file?

### ISSUE THREAD

**Issue by ArdxWe** [MeouSker77/ProgrammingRust#15]

**Comment by MeouSker77** [comment]
1. install `LaTex` environment: the Latex distribution and installation process are different on different OS, you can search how to install it in your system (recommend `tectonic`)
2. because the project uses `minted` package which is not standard package of LaTex, so you also need to install `python` and install `Pygments` using pip (`pip install Pygments`) (if you use distribution other than `tectonic`, you may need to install `minted` package itself)
3. then you can use `xelatex` or other compiler which supports Chinese (such as `tectonic` if you installed `tectonic` in step 1) to complile the `main.tex` file
    - note: you must use `-shell-escape` argument due to the using of `minted` package
    - if you use `tectonic`, then the command will be `tectonic -Z shell-escape main.tex`
    - if you use `xelatex`, then the command will be `xelatex -shell-escape main.tex`

**Comment by MeouSker77** [comment]
see this:
https://github.com/MeouSker77/ProgrammingRust#编译
